### PR TITLE
Fix GetOrphanRoot() and update checkpoint

### PR DESCRIPTION
**Pull request by l0rdicon**
GetOrphanRoot() was failing causing the stuck client sync issues. With this update the client syncs from the network without any issue. 

This was only tested on 2 vm's but both synced from the network without issues. Sync went through with no client resets required.

### CODE REVIEW

**Comment by l0rdicon** [comment]
If one or two more people can confirm this fixes the syncing issue before its merged it would be appreciated!

**Comment by kwentzell** [comment]
Stalling seems to be fixed for me. I'll let it run for a while, though.

The "ProcessBlock() : already have block xxxx" spam is still there though as reported in #269
Just so everyone is aware =D

**Comment by creativecuriosity** [comment]
Definitely still problems, but your(l0rdicon) reindex branch sync'd past 900k fresh; seems bogged down now.

**Comment by l0rdicon** [comment]
I'm going to close this for now until a full PR can be opened with all the updates

**Pull request closed without merging**
